development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: enc
  pool: 5
  username: root
  password: password
  host: localhost

test: &TEST
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: enc_test
  pool: 5
  username: root
  password: password
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: enc_prod
  pool: 5
  username: root
  password: password
  host: localhost
